#!/bin/bash

VERSION=v0.0.0

# set -e

help() {
  echo "Usage:"
  echo "  zmicro package install podman <args...>"
  echo ""
}

install() {
  pm install -y podman
  if [ "$?" != "0" ]; then
    log::error "failed to install podman ."
    return 1
  fi

  if [ "$(os::is_macos)" = "true" ]; then
    log::info "init podman machine ..."
    podman machine init
    if [ "$?" != "0" ]; then
      log::error "failed to init podman ."
      return 1
    fi

    log::info "start podman machine ..."
    podman machine start
    if [ "$?" != "0" ]; then
      log::error "failed to start podman ."
      return 1
    fi
  fi
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  if [ $? -eq 0 ]; then
    log::success "install podman success."
    exit 0
  else
    log::error "install podman failed."
    exit 1
  fi
}

run() {
  core $@
}

run $@
